### ISSUE TITLE
What's a "Cmd" key? 

### ISSUE THREAD

**Issue by stevedesmond-ca** [dabbott/react-native-express#12]
I'm just a dumb Windows user, and my keyboard doesn't have a "Cmd" key -- how do I bring up the dev menu? I also tried to shake my computer as suggested, but that didn't work either!

**Comment by dabbott** [comment]
Ahaha. I'm actually not sure... I am also not as familiar with the Android stuff in general.

On mac it's cmd + M, so I guess it should translate to... one of alt + M, ctrl + M, or windows + M (probably not that last one)?
