### ISSUE TITLE
nativebase.io not mentioned in the boilerplates list

### ISSUE THREAD

**Issue by jay-at-avido** [dabbott/react-native-express#17]
Disclamer:  I'm not affiliated to NativeBase at all.

So, I understand every list has a degree of subjectivity.
However I was left wondering why nativebase.io has not made the cut to the list of "worthy considering", as elsewhere I've see it mentioned alongside Pepperoni and Ignite as one of the top three.

**Comment by dabbott** [comment]
I think nativebase is worth mentioning, but under a component libraries section, since it isn't really a boilerplate.

I've been thinking of adding something on component libraries, including:
- Nativebase
- Shoutem
- React Native Elements

**Comment by nonameolsson** [comment]
I really think that NativeBase and React Native Elements should be mentioned under the section 4.2 and 4.3. 
What do you think about that @dabbott?

**Comment by dabbott** [comment]
Totally agree @nonameolsson. I probably don't have time to do it at the moment, but I'm happy to review PRs on this.
