### ISSUE TITLE
Just wanna say Thanks for writing this tutorial! it's very helpful!

### ISSUE THREAD

**Issue by 1c7** [dabbott/react-native-express#40]
spend 3-4 hour today watch the entire tutorial, very helpful!

Thanks!
(you guys can closed this issue whenever you want)

**Comment by 1c7** [comment]
I am building a simple Android App(use React Native of course) 

part of that App have a list, select image from album and the image would appear in list, 
then click "upload" would jump to other screen, 
that screen config upload option,  

then click "confirm", image should upload, 
and go right back to the list screen, and show upload progress.

I have no idea how to do that so searching tutorial online.

the tutorial you guys wrote are very helpful :)

I guess I should look into MobX and Redux and search something like "react native progress animation", that would probably solve my problem

**Comment by dabbott** [comment]
I'm glad you liked it! Good luck!
