### ISSUE TITLE
Code snippets are not correctly loading in Safari

### ISSUE THREAD

**Issue by aksswami** [dabbott/react-native-express#45]
<img width="1641" alt="screen shot 2018-02-27 at 5 29 48 pm" src="https://user-images.githubusercontent.com/1496758/36720768-eab77af4-1be3-11e8-8f69-3e9d31b7a9c4.png">

This problem is consistent with production as well as the local environment. As you can see the first-page code snippet is opening for all the pages.

**Comment by dabbott** [comment]
I think it's an HTTPS thing, but I'm not quite sure what. I think if I update the site to use HTTPS it'll work in safari again

**Comment by dabbott** [comment]
Fixed https://github.com/dabbott/react-native-express/pull/49
